const products = [
  {
    id: 1,
    name: "[고등어밥상]가시제거연구소 오렌지라벨 800g+800g 본사 고등어밥상 순살고등어",
    price: 24900,
    image: "/productImg/300(1).jpeg",
    freeShipping: true,
    smileShipping: false,
    bigSmileDay: true,
  },
  {
    id: 2,
    name: "[마이비]마이비 자연품은 얼룩제거제 리필(300ml)",
    price: 38600,
    image: "/productImg/300(2).jpeg",
    freeShipping: false,
    smileShipping: true,
    bigSmileDay: true,
  },
  {
    id: 3,
    name: "[제스프리]제스프리 골드키위 2kg 공식인증 점보",
    price: 26500,
    image: "/productImg/300(3).jpeg",
    freeShipping: true,
    smileShipping: false,
    bigSmileDay: false,
  },
  {
    id: 4,
    name: "지퍼락 실속팩 냉장 200매(소60+중100+대40)",
    price: 21500,
    image: "/productImg/300(4).jpeg",
    freeShipping: true,
    smileShipping: false,
    bigSmileDay: true,
  },
  {
    id: 5,
    name: "햇반 210g x24입",
    price: 20400,
    image: "/productImg/300(5).jpeg",
    freeShipping: true,
    smileShipping: false,
    bigSmileDay: true,
  },
  {
    id: 6,
    name: "3겹 데코앤소프트 37MX24롤 2팩 두루마리 화장지 휴지",
    price: 34120,
    image: "/productImg/300(6).jpeg",
    freeShipping: true,
    smileShipping: false,
    bigSmileDay: false,
  },
  {
    id: 7,
    name: "온더바디 발을씻자 코튼풋샴푸 자몽향 385ml 4개",
    price: 13980,
    image: "/productImg/300(7).jpeg",
    freeShipping: true,
    smileShipping: false,
    bigSmileDay: true,
  },
  {
    id: 8,
    name: "순수PURE천연펄프 25m 30롤 x 3팩 휴지",
    price: 29320,
    image: "/productImg/300(8).jpeg",
    freeShipping: true,
    smileShipping: false,
    bigSmileDay: false,
  },
  {
    id: 9,
    name: "다진마늘 2kg (1kg+1kg) 국내산 냉장",
    price: 13520,
    image: "/productImg/300(9).jpeg",
    freeShipping: false,
    smileShipping: true,
    bigSmileDay: true,
  },
  {
    id: 10,
    name: "게맛살/한성 크래미 몬스터크랩 72g X 15개 (쿠폰 13440원) (2세트 구매시 2천원 추가할인)",
    price: 13440,
    image: "/productImg/300(10).jpeg",
    freeShipping: true,
    smileShipping: true,
    bigSmileDay: true,
  },
  {
    id: 11,
    name: "20%+추가10% 코코리따/치크 최대80% 여름 베스트상품 특가",
    price: 7900,
    image: "/productImg/300(11).jpeg",
    freeShipping: true,
    smileShipping: false,
    bigSmileDay: true,
  },
  {
    id: 12,
    name: "(신세계의정부점) New Performance DURAMO 10 WIDE",
    price: 39920,
    image: "/productImg/300(12).jpeg",
    freeShipping: true,
    smileShipping: false,
    bigSmileDay: true,
  },
];

export default products;
